# Generated by Django 3.2 on 2022-11-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='hire_date',
            new_name='Date_of_release',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='role',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='bonus',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
    ]
