# Generated by Django 3.2 on 2022-11-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_auto_20221107_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='dept',
            new_name='theatre',
        ),
    ]
