# Generated by Django 3.2 on 2022-11-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0010_rename_department_theatre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='Genre',
        ),
    ]
